### ISSUE TITLE
Gettig following error : "Check failed to run: key not found: :ciphers"

### ISSUE THREAD

**Issue by nilroy** [sensu-plugins/sensu-plugins-elasticsearch#171]
Hi,

I used this asset from bonsai version 4.0.1 and created a check definition like below 

```
---
type: CheckConfig
metadata:
  name: elasticsearch-heap-check
  namespace: default
spec:
  command: "check-es-heap.rb --percentage -w 90 -c 95"
  high_flap_threshold: 0
  interval: 10
  ttl: 30
  low_flap_threshold: 0
  publish: true
  runtime_assets:
    - sensu-plugins-elasticsearch
    - sensu-ruby-runtime
  subscriptions:
    - system
  handlers:
    - pagerduty
```

But the check fails to run with error (Check failed to run: key not found: :ciphers)  pointing to rest-client. I found similar issues reported for rest-client version prior to 2.0.0. I also noticed that you updated the rest-client version in the master branch. When are you planning to release this asset in bonsai? 
@dependabot-preview @majormoses
